#import "../fragments/ProcessInstanceFragment.gql"
#import "../fragments/NodeInstanceFragment.gql"
#import "../fragments/ProcessTemplateFragment.gql"

query processInstance($id: Int!) {
    processInstance(filter: {id: $id}) {
        nodeElements {
            ...NodeInstanceFragment
        }
        template {
            ...ProcessTemplateFragment
        }
        ...ProcessInstanceFragment
    }
}