#import "../fragments/ProcessTemplateFragment.gql"
#import "../fragments/NodeTemplateFragment.gql"

query processTemplates_NTStart {
    processTemplates {
        nodeElements(filter: {
            implementationContains: "startevent"
        }) {
            ...NodeTemplateFragment
        }
        ...ProcessTemplateFragment
    }
}