#import "../fragments/UserFragment.gql"
#import "../fragments/UserMembershipFragment.gql"

query client {
  client: user {
    ...UserFragment
    membership {
      ...UserMembershipFragment
    }
  }
}
