#import "../fragments/NodeInstanceFragment.gql"

mutation releaseNodeInstance($idNI: Int!) {
    releaseNodeInstance(idNI: $idNI) {
        assignee {
            id 
            login 
        }
        ...NodeInstanceFragment
    }
}