mutation changeUserPassword( $login: String!, $newPassword: String!, $oldPassword: String!) {
    changeUserPassword(
        input: { newPassword: $newPassword, oldPassword: $oldPassword }, 
        filter: { login: $login }
    )
}