#import "./UserFragment.gql"

mutation login($login: String!, $password: String!, $expires: String) {
  login(input:{login: $login, password: $password, expires: $expires}) {
    token
  	user {
      ...user
    }
  }
}